var rectangleLength = 5;
var rectangleWidth = 3;
var rectangleArea = rectangleLength * rectangleWidth;
console.log(rectangleArea);
var rectanglePerimeter = 2 * (rectangleLength + rectangleWidth);
console.log(rectanglePerimeter);
var PI2 = 3.14159;
var circleRadius = 5;
var circleDiameter = circleRadius * 2;
var circleCircumference = 2 * PI2 * circleRadius;
var circleArea = PI2 * (Math.pow(5, 2));
console.log("diameter : ".concat(circleDiameter, " , circumference : ").concat(circleCircumference, " , area : ").concat(circleArea, " "));
var days = 366;
var sisaday = days % 365;
var sisayears = Math.round(days / 365);
var sisamonths = Math.round(sisaday / 30);
var sisadays = sisaday % 30;
console.log("".concat(sisayears, " year, ").concat(sisamonths, " month, ").concat(sisadays, " day "));
console.log("-----------------------------------------------------------");
var date1 = new Date("2022/01/20");
var date2 = new Date("2022/01/22");
var diff_in_days = Math.abs(date1.getDay() - date2.getDay());
var diff_in_months = Math.abs(date1.getMonth() - date2.getMonth());
var diff_in_years = Math.abs(date1.getFullYear() - date2.getFullYear());
console.log("".concat(diff_in_days, " days, ").concat(diff_in_months, " months, ").concat(diff_in_years, " years"));
